spring:
  application:
    name: task-service
  config:
    # Usamos o 'import' sem o 'optional:' para garantir que ele trave se não ler o servidor
    import: "configserver:http://localhost:8888"
  cloud:
    config:
      fail-fast: true # Força a aplicação a parar se não conseguir as configs
      retry:
        max-attempts: 5
  main:
    # Permite que as configs do servidor sobrescrevam qualquer tentativa local falha
    allow-bean-definition-overriding: true